### ISSUE TITLE
Unable to upload new folder, but works well on files in existing folders

### ISSUE THREAD

**Issue by ThomasPof** [lukasz-wronski/vscode-ftp-sync#180]
I'm using VScode Version 1.12.2 (1.12.2) and FTP-sync 0.3.3

When I try to upload a file which is inside an existing folder (remotly and locally), it works pretty well. But when I try to upload a new local folder (with right click -> Ftp-sync Upload), I've got this message 

`Ftp-sync: Uploading test3 failed: Error: Transfer aborted. Interrupted system call`

Same thing when I try to upload a file inside a folder which exist only locally. It works well if I create the folder remotly before the upload.

**Comment by clayms** [comment]
I am having the same problem.

Windows 10 Enterprise
VScode 1.22.1
ftp-sync 0.3.3

Files sync just fine, folders fail with the error message `Ftp-sync: Uploading Modeling failed: Error: Failure` .

**Comment by clayms** [comment]
It appears to be only when there are sub-directories.  There does not seem to be a problem when syncing a directory that has no sub-directories.  

Could it is a recursive flag `-r` is not getting set?

**Comment by clayms** [comment]
Some other strange things are happening.  When I tried to sync a folder that had no sub-directories, it apparently did so with no problem the first time, then is gave similar errors every time after that.  When I went to the remote computer and tried to `cd` into the folder and Linux told me that the file was not a directory.  When I  `cat`  the "file" it is blank.

**Comment by NajSurf** [comment]
fixed in #264

**Comment by isymbo** [comment]
still hit this issue with vscode 1.30.2 and FTP-sync 0.3.9

**Comment by nicschwartz** [comment]
I have this issue still as well. 
So, I end up having to login to the control panel on the host (ICDSoft) and delete the file that should be a directory. Then I have to create the directory and sync works fine. 

I'm running the following: 
ftp-sync: 0.3.9

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by rodneymelchers** [comment]
hey guys, i had this issue aswel.  What fixed it was this:

I changed the Owner of the folder to the same as the owner of the FTP acc

so went in by ssh and 

`chown  username folderpath -R `

everything worked fine after that
hope this helps
